name: Terraform Prod

on:
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/**'
      - 'envs/prod/**'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.1.7

      - name: Init backend
        run: terraform init -backend-config=../backend-prod.config -reconfigure

      - name: Validate
        run: terraform validate

      - name: Plan
        run: terraform plan -var-file=../envs/prod/terraform.tfvars
